security:
    password_hashers:
        App\Entity\Employe:
            algorithm: auto

    providers:
        app_employee_provider:
            id: App\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/_(profiler|wdt)
            security: false

        main:
            lazy: true
            provider: app_employee_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home
                username_parameter: username
                password_parameter: password
                enable_csrf: false
            logout:
                path: app_logout
                target: app_login
                invalidate_session: true
                delete_cookies:
                    - PHPSESSID
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week
                path: /
                always_remember_me: false

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/administrateur-rh, roles: ROLE_ADMINISTRATEUR_RH }
        - { path: ^/responsable-rh, roles: ROLE_RESPONSABLE_RH }
        - { path: ^/employee, roles: ROLE_EMPLOYEE }