<?php

namespace App\DataFixtures;

use App\Entity\Organisation;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class OrganisationFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $organisations = [
            ['DR00002', 'DAS - SIEGE', 'DSIG', 'FCZ', 'SFCZ', 'FONDATION CHEIKH ZAID'],
            ['DR00078', 'DAS - SIEGE', 'DSIG', 'FCZ', 'CCGA', 'DCGA - GROUPEMENT CONTROLE QUALITE'],
            ['DR00043', 'DAS - GESTION', 'DGST', 'FCZ', 'GACH', 'DGST - GROUPEMENTADMINISTRATION ACHAT CENTRALE ET GESTION DES COUTS'],
            ['DR00044', 'DAS - GESTION', 'DGST', 'FCZ', 'GCMP', 'DGST - GROUPEMENT COMPTABILITE GENERALE'],
            ['DR00046', 'DAS - GESTION', 'DGST', 'FCZ', 'GFIN', 'DGST - GROUPEMENT GESTION FINANCIERE DELEGUEE'],
            ['DR00047', 'DAS - GESTION', 'DGST', 'FCZ', 'GRSH', 'DGST - GROUPEMENT DES RESSOURCES HUMAINES'],
            ['DR00048', 'DAS - GESTION', 'DGST', 'FCZ', 'GJUR', 'DGST - GROUPEMENT JURIDIQUE'],
            ['DR00050', 'DAS - GESTION', 'DGST', 'FCZ', 'GBNQ', 'DGST - GROUPEMENT REGIE BANQUE : SERVICES BANQUE'],
            ['DR00095', 'DAS - GESTION', 'DGST', 'FCZ', 'GPRG', 'DGST - GROUPEMENT REGIE'],
            ['DR00008', 'DAS - ACTIVITE SOCIALE', 'DASO', 'FCZ', 'SUMM', 'DASO - SOC : SOINS UNITE MOBILE'],
            ['DR00037', 'DAS - ACTIVITE SOCIALE', 'DASO', 'FCZ', 'SASE', 'DASO - SOC : DIVERS ACTIVITE SOCIALES EXTERNES'],
            ['DR00049', 'DAS - ACTIVITE SOCIALE', 'DASO', 'FCZ', 'SPSI', 'DASO - SOC : PEC SOINS INTERNE'],
            ['DR00061', 'DAS - ACTIVITE SOCIALE', 'DASO', 'FCZ', 'SASI', 'DASO - SOC : DIVERS ACTIVITE SOCIALES INTERNES'],
            ['DR00096', 'DAS - ACTIVITE SOCIALE', 'DASO', 'FCZ', 'SPSE', 'DASO - SOC : PEC SOINS EXTERNE'],
            ['DR00003', 'DAS - ENSEIGNEMENT & FORMATION', 'DENS', 'FCZ', 'EUIA', 'DCGA - ENS - CENTRE FORMATION INITIALE - UIASS - RABAT'],
            ['DR00006', 'DAS - ENSEIGNEMENT & FORMATION', 'DENS', 'FCZ', 'ECSM', 'DENS - CENTRE SIMULATION RABAT- UIASS - RABAT'],
            ['DR00011', 'DAS - ENSEIGNEMENT & FORMATION', 'DENS', 'FCZ', 'IFCP', 'DENS - INSTITUT DE FORMATION AUX CARIERES PARAMEDICALES RABAT'],
            ['DR00027', 'DAS - ENSEIGNEMENT & FORMATION', 'DENS', 'FCZ', 'ECFC', 'DENS - CENTRE DE FORMATION CONTINUE ABULCASIS - UIASS - RABAT'],
            ['DR00029', 'DAS - ENSEIGNEMENT & FORMATION', 'DENS', 'FCZ', 'ECRI', 'DENS - CENTRE RESIDANAT ET D \'INTERNAT - UIASS - RABAT'],
            ['DR00030', 'DAS - ENSEIGNEMENT & FORMATION', 'DENS', 'FCZ', 'ELEZ', 'DENS - LYCEE D \'EXCELLENCE ZAHRAWI RABAT'],
            ['DR00057', 'DAS - ENSEIGNEMENT & FORMATION', 'DENS', 'FCZ', 'EEAS', 'DENS - ECOLE AFRICAINE DES SCIENCES DE LA SANTE - UIASS - RABAT'],
            ['DR00004', 'DAS - SOINS', 'DSOI', 'FCZ', 'SHCZ', 'DSOI - CHUR : HOPITAL UNIVERSITAIRE INTERNATIONAL CHEIKH ZAID RABAT'],
            ['DR00012', 'DAS - SOINS', 'DSOI', 'FCZ', 'SLMG', 'DSOI - CENTRE LABORATOIRE DU MAGHREB RABAT'],
            ['DR00013', 'DAS - SOINS', 'DSOI', 'FCZ', 'SDNT', 'DSOI - CENTRE DE SOINS ET DE RECHERCHES DENTAIRES CHEIKH ZAID RABAT'],
            ['DR00014', 'DAS - SOINS', 'DSOI', 'FCZ', 'SHMK', 'DSOI - HOPITAL MULTIDISCIPLINAIRE KHOURIBGA'],
            ['DR00015', 'DAS - SOINS', 'DSOI', 'FCZ', 'SHMB', 'DSOI - HOPITAL MULTIDISCIPLINAIRE BENGUERIR'],
            ['DR00016', 'DAS - SOINS', 'DSOI', 'FCZ', 'SHMY', 'DSOI - HOPITAL MULTIDISCIPLINAIRE YOUSSOUFIA'],
            ['DR00033', 'DAS - SOINS', 'DSOI', 'FCZ', 'SLPD', 'DSOI - CENTRE LABORATOIRE DE PROTHESES DENTAIRES FCZ'],
            ['DR00038', 'DAS - SOINS', 'DSOI', 'FCZ', 'SRAD', 'DSOI - CENTRE DE RADIOLOGIE - HUICZ'],
            ['DR00041', 'DAS - SOINS', 'DSOI', 'FCZ', 'SLAB', 'DSOI - CENTRE BIOLOGIE MEDCIALE ET ANAPATH - HUICZ'],
            ['DR00042', 'DAS - SOINS', 'DSOI', 'FCZ', 'SAHR', 'DSOI - CENTRE D ASSISTANCE ALLO HOPITAL ZONE CENTRALE'],
            ['DR00064', 'DAS - SOINS', 'DSOI', 'FCZ', 'SCOV', 'DSOI - CENTRE DE LUTTE ANTI-COVID'],
            ['DR00068', 'DAS - SOINS', 'DSOI', 'FCZ', 'SOPH', 'DSOI - CENTRE OPHTALMOLOGIQUE - HUICZ'],
            ['DR00069', 'DAS - SOINS', 'DSOI', 'FCZ', 'SKIN', 'DSOI - CENTRE KINESITHERAPIE - HUICZ'],
            ['DR00070', 'DAS - SOINS', 'DSOI', 'FCZ', 'SCVP', 'DSOI - CENTRE CCV PEDIATRIQUE - HUICZ'],
            ['DR00072', 'DAS - SOINS', 'DSOI', 'FCZ', 'SGHJ', 'DSOI - CENTRE GASTROLOGIE/HDJ - HUICZ'],
            ['DR00073', 'DAS - SOINS', 'DSOI', 'FCZ', 'SGYN', 'DSOI - CENTRE GYNECOLOGIE - HUICZ'],
            ['DR00074', 'DAS - SOINS', 'DSOI', 'FCZ', 'SURG', 'DSOI - CENTRE URGENCES - HUICZ'],
            ['DR00080', 'DAS - SOINS', 'DSOI', 'FCZ', 'SHMS', 'DSOI - HOPITAL MULTIDISCIPLINAIRE SAFI'],
            ['DR00082', 'DAS - SOINS', 'DSOI', 'FCZ', 'SHCT', 'DSOI - HOPITAL UNIVERSITAIRE INTERNATIONAL TANGER'],
            ['DR00094', 'DAS - SOINS', 'DSOI', 'FCZ', 'CSDA', 'DSOI - CENTRE DES SOINS ET DES RENCHERCHES DENTAIRES AIN ATIQ'],
            ['DR00010', 'DAS - HOTELLERIE-RESTAURATION', 'DRST', 'FCZ', 'RRUR', 'DRST - RESTAURATION : UIASS RESTAURANT RABAT'],
            ['DR00021', 'DAS - HOTELLERIE-RESTAURATION', 'DRST', 'FCZ', 'RHUR', 'DRST - HEBERGEMENT : UNIVERSITAIRE - 1 RABAT'],
            ['DR00022', 'DAS - HOTELLERIE-RESTAURATION', 'DRST', 'FCZ', 'RHAR', 'DRST - HEBERGEMENT : UNIVERSITAIRE - 2 RABAT'],
            ['DR00023', 'DAS - HOTELLERIE-RESTAURATION', 'DRST', 'FCZ', 'RRER', 'DRST - RESTAURATION : HCZ RESTAURANT RABAT'],
            ['DR00034', 'DAS - HOTELLERIE-RESTAURATION', 'DRST', 'FCZ', 'RRHK', 'DRST - RESTAURATION : HMK RESTAURANT KHOURIBGA'],
            ['DR00035', 'DAS - HOTELLERIE-RESTAURATION', 'DRST', 'FCZ', 'RRHY', 'DRST - RESTAURATION : HMY RESTAURANT YOUSSOUFIA'],
            ['DR00053', 'DAS - HOTELLERIE-RESTAURATION', 'DRST', 'FCZ', 'RDAR', 'DRST - RESTAURATION : DISTRIBUTEUR AUTOMATIQUES'],
            ['DR00076', 'DAS - HOTELLERIE-RESTAURATION', 'DRST', 'FCZ', 'RRHR', 'DRST - RESTAURATION : HEB UNIV-1 RESTAURANT RABAT'],
            ['DR00077', 'DAS - HOTELLERIE-RESTAURATION', 'DRST', 'FCZ', 'RHSR', 'DRST - RESTAURATION : HEB UNIV-1 SNACK PIZZERIA'],
            ['DR00085', 'DAS - HOTELLERIE-RESTAURATION', 'DRST', 'FCZ', 'RCER', 'DRST - RESTAURATION : HCZ L \'CASIS CAFETERIA'],
            ['DR00088', 'DAS - HOTELLERIE-RESTAURATION', 'DRST', 'FCZ', 'RBPR', 'DRST - RESTAURATION : HEB UNIV-1 BOULANGERIE PATISSERIE'],
            ['DR00089', 'DAS - HOTELLERIE-RESTAURATION', 'DRST', 'FCZ', 'RHCC', 'DRST - RESTAURATION : HEB UNIV-1 CAFETERIA'],
            ['DR00020', 'DAS - INFORMATIQUE ET NUMERIQUE', 'DNUM', 'FCZ', 'NSIT', 'DNUM - LA MAROCAINE DES SYSTEMES ET TECHNOLOGIES DE L \'INFORMATION'],
            ['DR00059', 'DAS - INFORMATIQUE ET NUMERIQUE', 'DNUM', 'FCZ', 'NARC', 'DNUM - ARCHIVAGE INSTITUTIONNEL'],
            ['DR00065', 'DAS - INFORMATIQUE ET NUMERIQUE', 'DNUM', 'FCZ', 'NITS', 'DNUM - LA MAROCAINE IT SERVICES'],
            ['DR00067', 'DAS - INFORMATIQUE ET NUMERIQUE', 'DNUM', 'FCZ', 'NNUM', 'DNUM -  GESTION DU NUMERIQUE'],
            ['DR00007', 'DAS - INGENIERIE & TRAVAUX', 'DING', 'FCZ', 'IMIN', 'DING - SOCIETE AFRICAINE DES SERVICES DE LA SANTE - MAINTENANCE TECHNIQUE'],
            ['DR00036', 'DAS - INGENIERIE & TRAVAUX', 'DING', 'FCZ', 'IEIS', 'DING - ETUDES ET INGENIERIE DE LA SANTE FCZ'],
            ['DR00045', 'DAS - INGENIERIE & TRAVAUX', 'DING', 'FCZ', 'ICCI', 'DING - CONTRÔLE COUTS METRES ACHATS'],
            ['DR00079', 'DAS - INGENIERIE & TRAVAUX', 'DING', 'FCZ', 'IESV', 'DING - REAMENAGEMENT & ESPACES VERTS RABAT'],
            ['DR00086', 'DAS - INGENIERIE & TRAVAUX', 'DING', 'FCZ', 'ISAE', 'DING - SOCIETE AFRICAINE DES SERVICES DE LA SANTE - ENGINS TRAVAUX'],
            ['DR00087', 'DAS - INGENIERIE & TRAVAUX', 'DING', 'FCZ', 'ISAM', 'DING - SOCIETE AFRICAINE DES SERVICES DE LA SANTE - MATERIEL TRAVAUX'],
            ['DR00092', 'DAS - INGENIERIE & TRAVAUX', 'DING', 'FCZ', 'IPTT', 'DING - SA2S TRAVAUX PARTICIPATION'],
            ['DR00018', 'DAS - LOGISTIQUE & APPROVISIONNEMENT', 'DAPR', 'FCZ', 'APCC', 'DAPR - A PP : APPROVISIONNEMENT CONSOMMABLE RABAT'],
            ['DR00019', 'DAS - LOGISTIQUE & APPROVISIONNEMENT', 'DAPR', 'FCZ', 'APVR', 'DAPR - LOG : PARC VEHICULES RABAT'],
            ['DR00032', 'DAS - LOGISTIQUE & APPROVISIONNEMENT', 'DAPR', 'FCZ', 'APUR', 'DAPR - LOG : PARKING AUTO RABAT'],
            ['DR00052', 'DAS - LOGISTIQUE & APPROVISIONNEMENT', 'DAPR', 'FCZ', 'APLM', 'DAPR - APP : PRODUITS CONSOMMABLE ALIMENTAIRE RABAT'],
            ['DR00091', 'DAS - LOGISTIQUE & APPROVISIONNEMENT', 'DAPR', 'FCZ', 'APCH', 'DAPR - APP : APPROVISIONNEMENT CONSOMMABLE CHANTIER RABAT'],
            ['DR00097', 'DAS - LOGISTIQUE & APPROVISIONNEMENT', 'DAPR', 'FCZ', 'LPDP', 'DAPR - LOG : LOGISTIQUE PHARMACEUTIQUE DISTRIB PHARMA'],
            ['DR00025', 'DAS - PHARMACEUTIQUE', 'DPHR', 'FCZ', 'PVPH', 'DPHR - POINT VENTE OFFICINE 1 PHARMACIE RABAT'],
            ['DR00058', 'DAS - PHARMACEUTIQUE', 'DPHR', 'FCZ', 'PPPH', 'DPHR -  PARAPHARMACIE RABAT'],
            ['DR00093', 'DAS - PHARMACEUTIQUE', 'DPHR', 'FCZ', 'PAMD', 'DPHR -  AFRIC MED PARTICIPATION'],
            ['DR00026', 'DAS - PRESTATIONS EXTERNALISEES & ACTIVITES DE PRODUCTION', 'DPRD', 'FCZ', 'PIMP', 'DPRD - CENTRE IMPREMERIE RABAT'],
            ['DR00090', 'DAS - PRESTATIONS EXTERNALISEES & ACTIVITES DE PRODUCTION', 'DPRD', 'FCZ', 'PPTM', 'DPRD - SA2S METIER PARTICIPATION'],
            ['DR00005', 'DAS - RECHERCHE & EXPERTISE', 'DEXP', 'FCZ', 'ECBE', 'DEXP - CENTRE DE BIOEQUIVALENCE RABAT'],
            ['DR00009', 'DAS - RECHERCHE & EXPERTISE', 'DEXP', 'FCZ', 'ECRG', 'DEXP - CENTRE DE GENOMIQUE CHEIKH ZAID'],
            ['DR00066', 'DAS - RECHERCHE & EXPERTISE', 'DEXP', 'FCZ', 'EEDF', 'DEXP - ECOLE DOCTORALE RABAT'],
            ['DR00028', 'DAS - SERVICES DE PROXIMITE', 'DSPR', 'FCZ', 'PTEX', 'DPRD - TEXTILE RABAT'],
            ['DR00054', 'DAS - SERVICES DE PROXIMITE', 'DSPR', 'FCZ', 'PBIR', 'DSPR - SERVICE : BLANCHISSERIE INDUSTRIELLE'],
            ['DR00056', 'DAS - SERVICES DE PROXIMITE', 'DSPR', 'FCZ', 'PLAV', 'DSPR - SERVICE : LAVOMATIC'],
            ['DR00063', 'DAS - SERVICES DE PROXIMITE', 'DSPR', 'FCZ', 'PCAP', 'DSPR - SERVICE : CENTRE D \'APPEL'],
            ['DR00081', 'DAS - SERVICES DE PROXIMITE', 'DSPR', 'FCZ', 'PEPC', 'DSPR - SERVICE : HBU1 EPICERIE RABAT'],
            ['DR00083', 'DAS - SERVICES DE PROXIMITE', 'DSPR', 'FCZ', 'PCOF', 'DSPR - SERVICE : COIFURE'],
            ['DR00084', 'DAS - SERVICES DE PROXIMITE', 'DSPR', 'FCZ', 'PEVN', 'DSPR - SERVICE : EVENEMENTIEL'],
            ['DR00017', 'AFRICMED - COMMERCIALISATION PHARMACEUTIQUE', 'EPHR', 'RGA', 'PGRO', 'LA MAROCAINE DU MEDICAMENT : AFRIC-MED REPARTITEUR GROSSISTE RABAT'],
            ['DR00040', 'SA2S - METIERS ET SERVICES', 'EPRD', 'SSS', 'PSMS', 'SOCIETE AFRICAINE DES SERVICES DE LA SANTE - METIERS SOINS RABAT'],
            ['DR00039', 'SA2S- INGENIERIE & TRAVAUX', 'EING', 'SST', 'ISAA', 'SA2S - TEC SOCIETE AFRICAINE DES SERVICES DE LA SANTE - TRAVAUX TECHNIQUES RABAT']
        ];

        foreach ($organisations as [$code, $divisionActivitesStrategiques, $das, $groupement, $dossier, $dossierDesignation]) {
            $organisation = new Organisation();
            $organisation->setCode($code);
            $organisation->setDivisionActivitesStrategiques($divisionActivitesStrategiques);
            $organisation->setDas($das);
            $organisation->setGroupement($groupement);
            $organisation->setDossier($dossier);
            $organisation->setDossierDesignation($dossierDesignation);
            
            $manager->persist($organisation);
        }

        $manager->flush();
    }
}
